services:
  - type: web
    name: twod3d-lottery
    env: docker
    rootDirectory: 2d3d-lottery-frontend
    dockerfilePath: ./Dockerfile
    dockerContext: ./2d3d-lottery-frontend
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: API_URL
        value: https://twod3d-lottery-api-q68w.onrender.com
      - key: APP_ENV
        value: production
      - key: PORT
        value: 10000
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
