services:
  - type: web
    name: twod3d-lottery
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://twod3d-lottery-api-q68w.onrender.com
    routes:
      # API routes
      - type: rewrite
        source: /api/*
        destination: https://twod3d-lottery-api-q68w.onrender.com/api/:splat

      # SPA routes - handle client-side routing
      - type: rewrite
        source: /*
        destination: /index.html

    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /index.html
        name: Cache-Control
        value: no-cache
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Access-Control-Allow-Origin
        value: https://twod3d-lottery-api-q68w.onrender.com 